### PR TITLE
fixing errors for C++11

### PR DESCRIPTION
**Pull request by lemo**
fixing two different types of errors:
* needed casts to proper type
* proper initialization of nif_functions

### CODE REVIEW

**Comment by lemo** [comment]
the travis build error is a linking problem with -lsnappy

**Comment by norton** [comment]
Thanks for the fixes and tip for linking.  The travis build error has been bugging me but I have not had the time to investigate.

**Comment by norton** [comment]
@lemo I pushed a subset of your changes to the dev branch.  

- Can you review the last 2 commits of the dev branch and then try the dev branch out?
- Can you show the diff that fixes the travis build error?  I don't see this issue on my local Mac OS X environment.

NOTE: The dev branch also contains @facebook/rocksdb as a backend to lets.

**Comment by norton** [comment]
@lemo I pushed a subset of your changes to the dev branch with other changes.  Can you review the dev branch?

The -lsnappy issue is resolved.  However, the travis build fails due to needing a newer version of gcc.

NOTE: The dev branch also contains @facebook/rocksdb as a backend to lets.

I will close this pull request.  Thank you for your feedback.

**Pull request closed without merging**
